# Name of workflow
name: hexlet-check

# Trigger the workflow on push or pull request
on:
  push:
    branchers:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions
/checkout@v2

      - name: Hexlet project check
      uses: hexlet/project-action@release